name: Flow Type Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flow_check:
    name: Run Flow Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use the version matching your project

      - name: Install dependencies
        run: npm install  # or yarn install if using yarn

      - name: Run Flow
        run: npx flow check
